SELECT name, job FROM emp WHERE job NOT IN("程序员");
SELECT name, sal, job FROM emp WHERE comm=300;
SELECT * FROM emp WHERE dept_id=1 AND sal>2000;
SELECT * FROM emp WHERE dept_id=3 OR sal=5000;
SELECT name FROM emp WHERE job IN("CEO", "项目经理");
SELECT * FROM emp WHERE sal IN(3000, 1500, 5000);
SELECT * FROM emp WHERE sal NOT IN(3000, 1500, 5000);
SELECT * FROM emp WHERE sal BETWEEN 1000 AND 2000;
SELECT * FROM emp WHERE sal NOT BETWEEN 1000 AND 2000;
SELECT name, manager FROM emp WHERE manager IS NOT NULL;
SELECT name, sal FROM emp WHERE manager IS NULL;
SELECT DISTINCT job FROM emp;
SELECT DISTINCT dept_id FROM emp;
SELECT name FROM emp WHERE name LIKE "孙%";
SELECT * FROM emp WHERE name LIKE "%精";
SELECT * FROM emp WHERE job LIKE "%销售%";
SELECT * FROM emp WHERE job LIKE "_售%";
SELECT * FROM emp WHERE name LIKE "%僧%" AND sal>2000;
SELECT * FROM emp WHERE dept_id IN(1, 2) AND job LIKE "市%";
SELECT name, sal FROM emp ORDER BY sal;
SELECT name, sal, dept_id FROM emp ORDER BY dept_id DESC, sal;
SELECT * FROM emp WHERE dept_id=3 AND sal>1500;
SELECT * FROM emp WHERE dept_id=2 AND manager IS NULL;
SELECT name FROM emp WHERE manager IS NOT NULL ORDER BY sal DESC;
SELECT name, hiredate FROM emp WHERE dept_id IN(2, 3) ORDER BY hiredate DESC;
SELECT name FROM emp WHERE name LIKE "%僧%" OR name LIKE "%精%";
SELECT DISTINCT job FROM emp WHERE sal>2000;
SELECT * FROM emp ORDER BY sal DESC LIMIT 3;
SELECT * FROM emp ORDER BY id LIMIT 5, 5;
SELECT * FROM emp ORDER BY id LIMIT 8, 4;
SELECT name, sal FROM emp WHERE dept_id=3 ORDER BY sal LIMIT 1;
SELECT * FROM emp WHERE NOT job="人事" ORDER BY sal DESC LIMIT 3, 3;
SELECT * FROM emp WHERE manager IS NULL AND dept_id=3 ORDER BY sal DESC LIMIT 3;
SELECT MAX(sal) FROM emp WHERE dept_id=2;
SELECT COUNT(*) FROM emp WHERE manager IS NOT NULL AND sal BETWEEN 1000 AND 2000;
SELECT SUM(sal) FROM emp WHERE dept_id=3;
SELECT COUNT(*) FROM emp WHERE job IN("程序员", "销售");
SELECT AVG(sal) FROM emp WHERE dept_id=1 AND manager IS NOT NULL;
SELECT MIN(sal), MAX(sal) FROM emp WHERE dept_id=1;
SELECT COUNT(*) FROM emp WHERE job LIKE "%销售%";
SELECT COUNT(*) FROM emp WHERE NOT sal IN(1500, 3000);
SELECT DISTINCT job FROM emp WHERE dept_id=1;
SELECT COUNT(*) FROM emp WHERE name LIKE "%精%";
SELECT SUM(sal) FROM emp WHERE job LIKE "%销售%";
SELECT MAX(sal) 最高工资, MIN(sal) 最低工资 FROM emp WHERE dept_id=2;
SELECT AVG(sal) FROM emp GROUP BY job;
SELECT MAX(sal) FROM emp GROUP BY dept_id;
SELECT MIN(sal) FROM emp GROUP BY job;
SELECT COUNT(*) FROM emp WHERE sal>2000 GROUP BY dept_id;
SELECT COUNT(*) FROM emp WHERE manager IS NOT NULL GROUP BY dept_id;
SELECT MIN(sal) FROM emp WHERE dept_id=1 GROUP BY job;
SELECT dept_id, AVG(sal) FROM emp GROUP BY dept_id ORDER BY AVG(sal) DESC LIMIT 1;